name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install a specific version
        uses: eifinger/setup-rye@v3
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          rye sync
          rye build --clean
          rye run coop-kobe-downloader
        env:
          LOGIN_ID: ${{ secrets.LOGIN_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
